CaseIndentation:
  IndentWhenRelativeTo: case
  IndentOneStep: true
Documentation:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Exclude:
    - lib/rgit/cli.rb
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 40