#!/usr/bin/env ruby
require 'rgit/rgit'
require 'i18n'
include Rgit
I18n.load_path << File.expand_path('../../locales/en.yml', __FILE__)
I18n.reload!

rgit = Rgit::Rgit.new(Configuration.exist? ? Configuration.load : Configuration.create)
Rgit::Cli.new(rgit).parse(ARGV)
